// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

namespace WebApplication1.Migrations
{
    [DbContext(typeof(OperaContext))]
    [Migration("20210516134432_SeedData2")]
    partial class SeedData2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication1.Models.Opera", b =>
                {
                    b.Property<int>("OperaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Composer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("OperaID");

                    b.ToTable("Operas");

                    b.HasData(
                        new
                        {
                            OperaID = 1,
                            Composer = "Wolfgang Amadeus Mozart",
                            Title = "Cosi Fan Tutte",
                            Year = 1790
                        },
                        new
                        {
                            OperaID = 2,
                            Composer = "Giuseppe Verdi",
                            Title = "Rigoletto",
                            Year = 1851
                        },
                        new
                        {
                            OperaID = 3,
                            Composer = "John Adams",
                            Title = "Nixon in China",
                            Year = 1987
                        },
                        new
                        {
                            OperaID = 4,
                            Composer = "Alban Berg",
                            Title = "Wozzeck",
                            Year = 1922
                        },
                        new
                        {
                            OperaID = 5,
                            Composer = "Wolfgang Amadeus Mozart",
                            Title = "Cosi Fan Tutte",
                            Year = 1790
                        },
                        new
                        {
                            OperaID = 6,
                            Composer = "Giuseppe Verdi",
                            Title = "Rigoletto",
                            Year = 1851
                        },
                        new
                        {
                            OperaID = 7,
                            Composer = "John Adams",
                            Title = "Nixon in China",
                            Year = 1987
                        },
                        new
                        {
                            OperaID = 8,
                            Composer = "Alban Berg",
                            Title = "Wozzeck",
                            Year = 1922
                        },
                        new
                        {
                            OperaID = 9,
                            Composer = "Wolfgang Amadeus Mozart",
                            Title = "Cosi Fan Tutte",
                            Year = 1790
                        },
                        new
                        {
                            OperaID = 10,
                            Composer = "Giuseppe Verdi",
                            Title = "Rigoletto",
                            Year = 1851
                        },
                        new
                        {
                            OperaID = 11,
                            Composer = "John Adams",
                            Title = "Nixon in China",
                            Year = 1987
                        },
                        new
                        {
                            OperaID = 12,
                            Composer = "Alban Berg",
                            Title = "Wozzeck",
                            Year = 1922
                        },
                        new
                        {
                            OperaID = 13,
                            Composer = "Wolfgang Amadeus Mozart",
                            Title = "Cosi Fan Tutte",
                            Year = 1790
                        },
                        new
                        {
                            OperaID = 14,
                            Composer = "Giuseppe Verdi",
                            Title = "Rigoletto",
                            Year = 1851
                        },
                        new
                        {
                            OperaID = 15,
                            Composer = "John Adams",
                            Title = "Nixon in China",
                            Year = 1987
                        },
                        new
                        {
                            OperaID = 16,
                            Composer = "Alban Berg",
                            Title = "Wozzeck",
                            Year = 1922
                        },
                        new
                        {
                            OperaID = 17,
                            Composer = "Wolfgang Amadeus Mozart",
                            Title = "Cosi Fan Tutte",
                            Year = 1790
                        },
                        new
                        {
                            OperaID = 18,
                            Composer = "Giuseppe Verdi",
                            Title = "Rigoletto",
                            Year = 1851
                        },
                        new
                        {
                            OperaID = 19,
                            Composer = "John Adams",
                            Title = "Nixon in China",
                            Year = 1987
                        },
                        new
                        {
                            OperaID = 20,
                            Composer = "Alban Berg",
                            Title = "Wozzeck",
                            Year = 1922
                        },
                        new
                        {
                            OperaID = 21,
                            Composer = "Wolfgang Amadeus Mozart",
                            Title = "Cosi Fan Tutte",
                            Year = 1790
                        },
                        new
                        {
                            OperaID = 22,
                            Composer = "Giuseppe Verdi",
                            Title = "Rigoletto",
                            Year = 1851
                        },
                        new
                        {
                            OperaID = 23,
                            Composer = "John Adams",
                            Title = "Nixon in China",
                            Year = 1987
                        },
                        new
                        {
                            OperaID = 24,
                            Composer = "Alban Berg",
                            Title = "Wozzeck",
                            Year = 1922
                        },
                        new
                        {
                            OperaID = 25,
                            Composer = "Wolfgang Amadeus Mozart",
                            Title = "Cosi Fan Tutte",
                            Year = 1790
                        },
                        new
                        {
                            OperaID = 26,
                            Composer = "Giuseppe Verdi",
                            Title = "Rigoletto",
                            Year = 1851
                        },
                        new
                        {
                            OperaID = 27,
                            Composer = "John Adams",
                            Title = "Nixon in China",
                            Year = 1987
                        },
                        new
                        {
                            OperaID = 28,
                            Composer = "Alban Berg",
                            Title = "Wozzeck",
                            Year = 1922
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
